# Generated by Django 5.2.5 on 2026-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_exam_additional_info_scheme_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('company_or_org', models.CharField(blank=True, max_length=255)),
                ('opportunity_type', models.CharField(choices=[('government_job', 'Government Job'), ('private_job', 'Private Job'), ('it_offcampus', 'IT Off-Campus'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('job_fair', 'Job Fair'), ('career_portal', 'Career Portal')], default='private_job', max_length=40)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, default='All India', max_length=120)),
                ('qualification', models.CharField(blank=True, max_length=160)),
                ('required_skills', models.TextField(blank=True)),
                ('min_10th_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_12th_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('salary_or_stipend', models.CharField(blank=True, max_length=160)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('is_live_source', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['deadline', 'title'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_10_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_12_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester_marks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
