# Generated by Django 5.2.5 on 2026-04-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_jobopportunity_userprofile_class_10_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobopportunity',
            options={'ordering': ['registration_end_date', 'deadline', 'title']},
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='compensation',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='compensation_type',
            field=models.CharField(choices=[('not_listed', 'Not Listed'), ('ctc', 'CTC'), ('salary', 'Salary'), ('stipend', 'Stipend'), ('pay_scale', 'Pay Scale'), ('benefit', 'Benefit')], default='not_listed', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='official_notification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopportunity',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
    ]
