# Generated by Django 5.2.5 on 2026-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_alter_jobopportunity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='application_fee',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='exam',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='conducting_body',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='exam',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_live_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='official_notification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='salary_package',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefit_amount',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='scheme',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_live_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='official_notification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='required_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='scheme',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
    ]
